### ISSUE TITLE
Unable to run Spider-Man: Web of Shadows – The Amazing Allies Edition (ULES01174) on the PSP 3000

### ISSUE THREAD

**Issue by Windows10User2** [PSP-Archive/ARK-4#68]
When running Spider-Man: Web of Shadows – The Amazing Allies Edition (ULES01174) on the PSP 3000, I have an error (80010016).

**Comment by JoseAaronLopezGarcia** [comment]
Can you be a bit more detailed in your reports?
What format are you using? ISO, CSO, PBP, etc
Is it a decrypted PBP or encrypted PBP?

**Comment by Windows10User2** [comment]
> Can you be a bit more detailed in your reports? What format are you using? ISO, CSO, PBP, etc Is it a decrypted PBP or encrypted PBP?

ISO. What do you mean by decrypted or encrypted PBP?

**Comment by JoseAaronLopezGarcia** [comment]
What are you doing to break so many things?
I just tried the game and had no issues at all.

**Comment by TheSubPlayer** [comment]
I also tested the game and it's working normally, do you have any plugins active?

**Comment by JoseAaronLopezGarcia** [comment]
Closing this since it's not condfirmed to be ARK's issue.

**Comment by Windows10User2** [comment]
> What are you doing to break so many things? I just tried the game and had no issues at all.

Nothing, it's the only game that doesn't work and other users complaing about the other problems as well.



> I also tested the game and it's working normally, do you have any plugins active?

No.



> Closing this since it's confirmed to not be ARK's issue.

Since when?

**Comment by JoseAaronLopezGarcia** [comment]
>
> Since when?
> 

Since I and others have tested it and found it to be no issue at all.
The issue is on your end, perhaps a corrupted ISO or memory card.

**Comment by Windows10User2** [comment]
> > Since when?
> 
> Since I and others have tested it and found it to be no issue at all. The issue is on your end, perhaps a corrupted ISO or memory card.

I mean, since when did they state their issues were fixed?

I tried a lof of different ISOs and microSD cards/SD2VITAs.

**Comment by JoseAaronLopezGarcia** [comment]
> > > Since when?
> > 
> > 
> > Since I and others have tested it and found it to be no issue at all. The issue is on your end, perhaps a corrupted ISO or memory card.
> 
> I mean, since when did they state their issues were fixed?
> 
> I tried a lof of different ISOs and microSD cards/SD2VITAs.

SD2Vita? Didn't you report the issue for PSP3000?

They stated the issues (with 3.65) were solved when I updated ARK to support 3.65 a while back.
The issue you are getting is because you are not installing K.BIN file correctly and at this point I'm not willing to continue this conversation as it's not related to any issues within ARK itself.

**Comment by Windows10User2** [comment]
> > > > Since when?
> > > 
> > > 
> > > Since I and others have tested it and found it to be no issue at all. The issue is on your end, perhaps a corrupted ISO or memory card.
> > 
> > 
> > I mean, since when did they state their issues were fixed?
> > I tried a lof of different ISOs and microSD cards/SD2VITAs.
> 
> SD2Vita? Didn't you report the issue for PSP3000?
> 
> They stated the issues (with 3.65) were solved when I updated ARK to support 3.65 a while back. The issue you are getting is because you are not installing K.BIN file correctly and at this point I'm not willing to continue this conversation as it's not related to any issues within ARK itself.

Sorry, I didn't mean SD2VITAs but microSD adapters. It's for the PSP 3000. How can I fix this issue?

What +3.65 issues on the PS Vita/PS TV are you talking about since I never had that FW version (I always had the 3.60 one) installed and I still have these issues (the boot one and the C1-2858-3 ones) since the beginning?

How can I not be installing it the right way since I deleted the ARK_01234 folder created by FastARK, transferred the downloaded one to the PS Vita and replaced its K.BIN file for the one in the downloaded VitaBubble folder and now it worked for the PS TV and not for the PS Vita? It is related to ARK unlike what you say.

**Comment by Windows10User2** [comment]
After replacing the  "–" in the ISO filename with a "-", I stopped having the issue which prevented me from playing this game [Spider-Man: Web of Shadows – The Amazing Allies Edition (ULES01174)].
